"""Tests for phase-gradient rotations generated by controlled addition."""

from typing import no_type_check

import numpy as np
import pytest
from guppylang import comptime, guppy
from guppylang.std.debug import state_output
from guppylang.std.quantum import discard, discard_array, qubit, x
from selene_sim import Quest

from guppyalgos.primitives.rotations import (
    RotationPhaseGradient,
    RotationAxis,
    RotationAxisX,
    RotationAxisY,
    RotationAxisZ,
)
from guppyalgos.primitives.state_preparation.phase_gradient import (
    Convention,
    phase_gradient,
)
from guppyalgos.utils import qarray
from guppyalgos.testing import assert_allclose_ignorephase


def _axis_expected_state(theta: float, axis: str) -> np.ndarray:
    """Return the expected ancilla state after a total axis rotation `theta`."""
    phase = np.pi * theta / 2.0
    if axis == "x":
        return np.array([np.cos(phase), -1j * np.sin(phase)], dtype=np.complex128)
    if axis == "y":
        return np.array([np.cos(phase), np.sin(phase)], dtype=np.complex128)
    return np.array([np.exp(-1j * phase), 0.0], dtype=np.complex128)


@pytest.mark.parametrize(
    ("bits", "axis", "axis_type"),
    [
        ([True, False, True], "y", RotationAxisY),
        ([False, True, True], "x", RotationAxisX),
        ([True, True, False, False], "z", RotationAxisZ),
        ([True, True, True, True], "y", RotationAxisY),
        ([False, False, False], "x", RotationAxisX),
        ([False, True, False, False], "z", RotationAxisZ),
    ],
)
def test_phase_gradient_rotations(
    bits: list[bool],
    axis: str,
    axis_type: type[RotationAxis],
) -> None:
    """Check kicked-back rotation using the register-incremented style.

    For a phase gradient state on ``d`` qubits, adding the ``d``-bit integer ``x``
    multiplies the register by ``exp(-2π i x / 2^d)``. The phase-gradient struct
    uses the default positive convention: it applies ``X`` to the target before
    and after the controlled adder, so addition occurs on the original ``|0>``
    branch and kicks back a positive half-turn parameter
    ``theta = 2 * x / 2^d`` on the ancilla.
    """
    n_phase_qubits = len(bits)
    prep = phase_gradient(n_phase_qubits, convention=Convention.Standard)

    @guppy
    @no_type_check
    def main() -> None:
        idx = comptime(bits)
        phase_qreg = qarray(comptime(n_phase_qubits))
        phase_gradient_state = qarray(comptime(n_phase_qubits))
        rotation_target = qubit()

        for bit in range(comptime(n_phase_qubits)):
            if idx[bit]:
                x(phase_qreg[bit])

        prep(phase_gradient_state)
        rotation = RotationPhaseGradient(phase_gradient_state, axis_type())
        rotation.compose(phase_qreg, rotation_target)

        state_output("ancilla", rotation_target)
        discard_array(phase_qreg)
        discard_array(rotation.phase_gradient)
        discard(rotation_target)

    res = main.emulator(n_qubits=(3 * n_phase_qubits) + 1).run()
    states = Quest.extract_states_dict(res.results[0].entries)
    ancilla_state = states["ancilla"].get_single_state()

    encoded_integer = sum((2**i) for i, bit in enumerate(bits) if bit)
    expected_theta = float(2.0 * encoded_integer / (2**n_phase_qubits))
    expected_state = _axis_expected_state(expected_theta, axis)
    assert_allclose_ignorephase(ancilla_state, expected_state)
