"""Comparators for comparing the values of two registers."""

from typing import no_type_check

from guppylang import array, guppy, qubit
from guppylang.std.builtins import nat
from guppylang.std.quantum import cx, x, toffoli, discard

from guppyalgos.utils import transversal
from guppyalgos.primitives.gate_decompositions.and_op import (
    temp_and_compute,
    temp_and_uncompute,
)

from guppyalgos.primitives.subroutines.ladders import CXLadderLinear
from guppyalgos.utils.guppy.unsafe_borrow import (
    _unsafe_array_borrow_slice,
    _unsafe_array_unborrow_slice,
)


@guppy
@no_type_check
def _maj_umaj_bottom_carry_out_partial_gate(
    a: qubit,
    b: qubit,
    c: qubit,
    target: qubit,
    inverse: bool,
    uncompute_target: bool,
) -> None:
    """Apply the merged final MAJ/MAJ† step of a ripple-carry comparator.

    This gate acts on the most-significant bit of the addition. It is
    equivalent to applying a majority gate, copying the resulting final
    carry into ``target``, and then applying the inverse of the
    majority gate.

    The common operations in the MAJ and MAJ† gates are canceled, giving
    the reduced sequence implemented below. The input qubits ``a``, ``b``,
    and ``c`` are restored as required by the surrounding ripple, while
    ``target`` is flipped iff the addition produces a final carry.

    Args:
        a: Most-significant qubit of the first input register. Unchanged by
            the operation.
        b: Most-significant qubit of the second input/output register.
            Unchanged by the operation.
        c: Carry qubit from the preceding ripple stage.
        target: Target qubit into which the carry-out result is computed.
        inverse: If ``False``, apply the forward half. If ``True``, complete
            the uncomputation of the forward half.
        uncompute_target: If ``True``, uncompute the target when ``inverse``
            is ``True``.

    Circuit:
        a: ──■────■───────■────■────■─────
             │    │       │    │    │
        b: ──X────┼───■───┼────┼────X─────
                  │   │   │    │
        c: ───────X───■───┼────X──────────
                      │   │
        0: ───────────X───X───────────────

    """
    if not inverse:
        cx(a, b)
        cx(a, c)

        # Could use temp_and_compute with a clean target
        toffoli(c, b, target)
        cx(a, target)

    else:
        if uncompute_target:
            cx(a, target)
            # Could use temp_and_uncompute with a clean target
            toffoli(c, b, target)

        cx(a, c)
        cx(a, b)


@guppy
@no_type_check
def partial_comparator_ripple_cuccaro[n: nat](
    a_reg: array[qubit, n],
    b_reg: array[qubit, n],
    target: qubit,
    ancilla: qubit,
    inverse: bool,
    uncompute_target: bool,
) -> None:
    """Apply one half of a complement-based Cuccaro ripple-carry comparator.

    The two halves must be applied using the same ``ancilla`` qubit.

    With ``inverse=False``, the circuit computes ``a < b`` into ``target``.
    It uses the carry generated by the one's-complement subtraction

        (a - b) mod 2**n = ~(~a + b) mod 2**n.

    The forward half computes the majority ripple, computes the final carry into
    ``target``, and uncomputes all carry qubits except the least-significant
    majority operation. Consequently, ``a_reg``, ``b_reg``, and ``ancilla``
    remain in an intermediate state.

    With ``inverse=True``, the circuit completes the uncomputation by undoing
    the remaining least-significant majority operation and restoring the
    complement applied to ``b_reg``. This half must therefore be applied to
    the state produced by the forward half using the same ``ancilla``.

    Applying the two halves consecutively implements

        ``|a>|b>|t> -> |a>|b>|(a < b)>``.

    Related comparisons can be obtained by modifying the inputs or output:

    - Negating the result computes ``a >= b``.
    - Swapping ``a_reg`` and ``b_reg`` computes ``b < a``.
    - Swapping the registers and negating the result computes ``b >= a``.

    Reference:
    Cuccaro, Steven A., et al. "A new quantum ripple-carry addition
    circuit." arXiv preprint quant-ph/0410184 (2004).

    Args:
        a_reg (array[qubit, n]): Register containing ``a``. Unchanged by the
            operation.
        b_reg (array[qubit, n]): Register containing ``b``. Unchanged by the
            operation.
        target (qubit): Target qubit into which the comparison result is computed.
            It is flipped iff ``b < a``.
        ancilla: Workspace qubit shared between the two halves. It must start
            in ``|0>`` before the forward half and is restored to ``|0>``
            after the inverse half.
        inverse: If ``False``, apply the forward half. If ``True``, complete
            the uncomputation of the forward half.
        uncompute_target: If ``True``, uncompute the target when ``inverse``
            is ``True``.

    """
    cx_ladder = CXLadderLinear()

    if not inverse:
        transversal(x, a_reg)

        if n == 1:
            # Could use temp_and_compute with a clean target
            toffoli(a_reg[0], b_reg[0], target)
            cx(a_reg[0], b_reg[0])

        elif n == 2:
            # Boundary MAJ: carry-in is known to be 0 and ancilla is clean.
            temp_and_compute(a_reg[0], b_reg[0], ancilla)

            _maj_umaj_bottom_carry_out_partial_gate(
                a_reg[1], b_reg[1], ancilla, target, False, False
            )

        else:
            ## Forward pass
            transversal(cx, a_reg, b_reg, 1, n)

            temp_and_compute(a_reg[0], b_reg[0], ancilla)

            # Forward n-1 CX ladder
            cx(a_reg[1], ancilla)
            cx_p, cx_q, cx_s = _unsafe_array_borrow_slice(a_reg, 1, comptime(n - 1), 0)
            cx_ladder.descending_dagger(cx_q)
            _unsafe_array_unborrow_slice(a_reg, cx_p, cx_q, cx_s)

            # Forward n-2 Toffoli ladder
            toffoli(ancilla, b_reg[1], a_reg[1])
            for i in range(n - 3):
                toffoli(a_reg[i + 1], b_reg[i + 2], a_reg[i + 2])

            # Could use temp_and_compute with a clean target
            toffoli(a_reg[n - 2], b_reg[n - 1], target)
            cx(a_reg[n - 1], target)

    else:
        if n == 1:
            cx(a_reg[0], b_reg[0])
            if uncompute_target:
                # Could use temp_and_uncompute with a clean target
                toffoli(a_reg[0], b_reg[0], target)

        elif n == 2:
            _maj_umaj_bottom_carry_out_partial_gate(
                a_reg[1], b_reg[1], ancilla, target, True, uncompute_target
            )
            temp_and_uncompute(a_reg[0], b_reg[0], ancilla)

        else:
            if uncompute_target:
                cx(a_reg[n - 1], target)
                # Could use temp_and_uncompute with a clean target
                toffoli(a_reg[n - 2], b_reg[n - 1], target)

            ## Reverse pass
            # Reverse n-2 Toffoli ladder
            for i in range(n - 3):
                toffoli(a_reg[n - i - 3], b_reg[n - i - 2], a_reg[n - i - 2])
            toffoli(ancilla, b_reg[1], a_reg[1])

            # Reverse n-1 CX ladder
            cx_p, cx_q, cx_s = _unsafe_array_borrow_slice(a_reg, 1, comptime(n - 1), 0)
            cx_ladder.descending(cx_q)
            _unsafe_array_unborrow_slice(a_reg, cx_p, cx_q, cx_s)
            cx(a_reg[1], ancilla)

            temp_and_uncompute(a_reg[0], b_reg[0], ancilla)

            transversal(cx, a_reg, b_reg, 1, n)

        transversal(x, a_reg)


@guppy
@no_type_check
def comparator_ripple_cuccaro[n: nat](
    a_reg: array[qubit, n], b_reg: array[qubit, n], target: qubit
) -> None:
    """Compare two integers using complement-based Cuccaro ripple-carry subtraction.

    The circuit computes ``a < b`` and computes the result into ``target`` while
    leaving ``a_reg`` and ``b_reg`` unchanged.

    The comparison is obtained from the carry produced by the modular subtraction

        (a - b) mod 2**n = ~(~a + b) mod 2**n.

    Only the carry-propagation part of the subtraction is required to determine
    whether ``a < b``. The circuit therefore applies the majority ripple to
    compute the carry, computes the resulting comparison bit into ``target``, and
    then applies the inverse of the majority ripple to restore the input registers.

    This construction uses one's-complement arithmetic but does not perform an
    end-around carry, since only the carry information is needed for the
    comparison.

    Related comparisons can be obtained by modifying the inputs or output:

    - Negating the result computes ``a >= b``.
    - Swapping ``a_reg`` and ``b_reg`` computes ``b < a``.
    - Swapping the registers and negating the result computes ``b >= a``.

    Reference:
    Cuccaro, Steven A., et al. "A new quantum ripple-carry addition
    circuit." arXiv preprint quant-ph/0410184 (2004).

    Args:
        a_reg (array[qubit, n]): Register containing ``a``. Unchanged by the
            operation.
        b_reg (array[qubit, n]): Register containing ``b``. Unchanged by the
            operation.
        target (qubit): Target qubit into which the comparison result is computed.
            It is flipped iff ``a < b``.

    """
    ancilla = qubit()

    partial_comparator_ripple_cuccaro(
        a_reg,
        b_reg,
        target,
        ancilla,
        False,
        False,
    )

    partial_comparator_ripple_cuccaro(
        a_reg,
        b_reg,
        target,
        ancilla,
        True,
        False,
    )

    discard(ancilla)
